model: resnet
batch_size: 32
n_epochs: 100
learning_rate: 0.001

resnet:
  kernel: 19
  padding: 5
  stride: 3
  block: basic
  n_layers: 10
  blocks: [1,1,1,1,1,1,1,1,1,1]
  channels: [20,30,45,67,100,150,225,337,505,757]
  n_classes: 2
