tcn:
  n_filters: 25
  n_layers: 4
  kernel_size: 2
  dropout: 0.2
  n_classes: 2
  in_chan: 1

resnet:
  kernel: 19
  padding: 5
  stride: 3
  block: bottleneck
  n_layers: 4
  layer_blocks: [2,2,2,2]
  layer_channels: [20,30,45,67]

