model: resnet
# batch_size: 1000
batch_size: 64
n_epochs: 50
learning_rate: 0.001

tcn:
  n_filters: 25
  n_layers: 4
  kernel: 2
  dropout: 0.2
  n_classes: 2
  in_chan: 1

resnet:
  kernel: 19
  padding: 5  # TODO: How was this calculated?
  stride: 3
  block: bottleneck
  n_layers: 4
  blocks: [2,2,2,2]
  channels: [20,30,45,67]
  n_classes: 2

cnn:
  n_layers: 4
  channels: [20,30,45,67]
  kernels: [3,3,3,3]
  n_classes: 2
  classifier: gap_fc # fc / gap_fc / gap

cnn_rnn:
  n_conv_layers: 4
  channels: [20,30,45,67]
  kernels: [3,3,3,3]
  n_rec_layers: 2
  cell: lstm # TODO: also implement GRU
  hidden: 50
  dropout: 0.2
  bidirectional: True
  n_classes: 2



