model: resnet
# batch_size: 1000
batch_size: 64
n_epochs: 50
learning_rate: 0.001

tcn:
  n_filters: 25
  n_layers: 4
  kernel_size: 2
  dropout: 0.2
  n_classes: 2
  in_chan: 1

resnet:
  kernel_size: 19
  padding: 5
  stride: 3
  block: bottleneck
  n_layers: 4
  layer_blocks: [2,2,2,2]
  layer_channels: [20,30,45,67]
  n_classes: 2

cnn:
  n_layers: 4
  layer_channels: [20,30,45,67]
  layer_kernels: [3,3,3,3]
  n_classes: 2


lstm:


cnn+lstm:
  